spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jihae185@gmail.com
    password: afjncmryqrhrkqqw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
    auth-code-expiration-millis: 1800000

